package com.webmedicalportaldemo.model;

public class HospitalAdmin extends Employee {

    private static final String HOSPITAL_ADMIN_ROLE = "HOSPITAL_ADMIN";

    /**
     * Default constructor for DAO mapping and object creation.
     */
    public HospitalAdmin() {
        super();
        setRole(HOSPITAL_ADMIN_ROLE);
        setActive(true);
    }

    /**
     * Constructor for registering a new hospital administrator.
     * The userId is generated by MySQL upon insertion.
     */
    public HospitalAdmin(
            String firstName,
            String lastName,
            String email,
            String password,
            String employeeId,
            String department) {

        super();
        setFirstName(firstName);
        setLastName(lastName);
        setEmail(email);
        setPassword(password);
        setRole(HOSPITAL_ADMIN_ROLE);
        setEmployeeId(employeeId);
        setDepartment(department);
        setActive(true);
    }

    /**
     * Constructor for loading an existing hospital administrator from the database.
     */
    public HospitalAdmin(
            int userId,
            String firstName,
            String lastName,
            String email,
            String password,
            String employeeId,
            String department,
            boolean active) {

        super();
        setUserId(userId);
        setFirstName(firstName);
        setLastName(lastName);
        setEmail(email);
        setPassword(password);
        setRole(HOSPITAL_ADMIN_ROLE);
        setEmployeeId(employeeId);
        setDepartment(department);
        setActive(active);
    }

    /**
     * Lightweight constructor for administrator lists.
     */
    public HospitalAdmin(
            int userId,
            String firstName,
            String lastName,
            String employeeId) {

        super();
        setUserId(userId);
        setFirstName(firstName);
        setLastName(lastName);
        setEmployeeId(employeeId);
        setRole(HOSPITAL_ADMIN_ROLE);
        setActive(true);
    }

    /**
     * Updates profile fields without overwriting an existing password with an empty string.
     */
    public void updateHospitalAdmin(
            int userId,
            String firstName,
            String lastName,
            String email,
            String password,
            String department) {

        setUserId(userId);
        setFirstName(firstName);
        setLastName(lastName);
        setEmail(email);
        setDepartment(department);
        setRole(HOSPITAL_ADMIN_ROLE);

        if (password != null && !password.isBlank()) {
            setPassword(password);
        }
    }

    public String getInteractionType() {
        return "HOSPITAL_ADMIN_CONTROL_SESSION";
    }

    public String getDisplaySummary() {
        return "Hospital Administrator: "
                + getFullName()
                + " (User ID: #"
                + getUserId()
                + ", Employee ID: "
                + getEmployeeId()
                + ") has opened the hospital administration console.";
    }

    public void displayDashboard() {
        System.out.println("Displaying Hospital Administrator Portal for: " + getFullName());
    }

    public void generateReport() {
        System.out.println("Generating hospital administration reports...");
    }

    @Override
    public String toString() {
        return "HospitalAdmin{" +
                "userId=" + getUserId() +
                ", employeeId='" + getEmployeeId() + '\'' +
                ", firstName='" + getFirstName() + '\'' +
                ", lastName='" + getLastName() + '\'' +
                ", email='" + getEmail() + '\'' +
                ", role='" + getRole() + '\'' +
                ", department='" + getDepartment() + '\'' +
                ", active=" + isActive() +
                '}';
    }
}